"""add_team_id

Revision ID: 614796f0d734
Revises: c4f4fd4e6fb5
Create Date: 2025-11-13 17:02:30.282192

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "614796f0d734"
down_revision = "c4f4fd4e6fb5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for data migration ###

    op.add_column("assistant", sa.Column("team_id", sa.Text(), nullable=True))
    op.execute("UPDATE assistant SET team_id = user_id")
    op.alter_column("assistant", "team_id", existing_type=sa.Text(), nullable=False)

    op.drop_index(op.f("idx_assistant_user"), table_name="assistant")
    op.create_index("idx_assistant_user", "assistant", ["team_id"], unique=False)
    op.drop_index(op.f("idx_assistant_user_assistant"), table_name="assistant")
    op.create_index(
        "idx_assistant_user_assistant",
        "assistant",
        ["team_id", "assistant_id"],
        unique=True,
    )

    op.drop_column("assistant", "user_id")

    op.add_column("runs", sa.Column("team_id", sa.Text(), nullable=True))
    op.execute("UPDATE runs SET team_id = user_id")
    op.execute("UPDATE runs SET user_id = 'system'")
    op.alter_column("runs", "team_id", existing_type=sa.Text(), nullable=False)

    op.create_index("idx_runs_team", "runs", ["team_id"], unique=False)
    op.create_index("idx_runs_team_user", "runs", ["team_id", "user_id"], unique=False)

    op.add_column("thread", sa.Column("team_id", sa.Text(), nullable=True))
    op.execute("UPDATE thread SET team_id = user_id")
    op.execute("UPDATE thread SET user_id = 'system'")
    op.alter_column("thread", "team_id", existing_type=sa.Text(), nullable=False)

    op.create_index("idx_thread_team", "thread", ["team_id"], unique=False)
    op.create_index(
        "idx_thread_team_user", "thread", ["team_id", "user_id"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index("idx_thread_team_user", table_name="thread")
    op.drop_index("idx_thread_team", table_name="thread")
    op.drop_column("thread", "team_id")

    op.drop_index("idx_runs_team_user", table_name="runs")
    op.drop_index("idx_runs_team", table_name="runs")
    op.drop_column("runs", "team_id")

    op.add_column(
        "assistant", sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.execute("UPDATE assistant SET user_id = team_id")
    op.alter_column("assistant", "user_id", existing_type=sa.TEXT(), nullable=False)

    op.drop_index("idx_assistant_user_assistant", table_name="assistant")
    op.create_index(
        op.f("idx_assistant_user_assistant"),
        "assistant",
        ["user_id", "assistant_id"],
        unique=True,
    )
    op.drop_index("idx_assistant_user", table_name="assistant")
    op.create_index(op.f("idx_assistant_user"), "assistant", ["user_id"], unique=False)

    op.drop_column("assistant", "team_id")
