"""add_soft_delete_fields

Revision ID: 5b125b55a942
Revises: 34ecbe1e8783
Create Date: 2025-11-10 14:25:24.624918

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5b125b55a942"
down_revision = "34ecbe1e8783"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assistant", sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True)
    )
    op.create_index(
        "idx_assistant_deleted_at", "assistant", ["deleted_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_assistant_deleted_at", table_name="assistant")
    op.drop_column("assistant", "deleted_at")
    # ### end Alembic commands ###
