"""add_thread_assistant_id_and_is_shared

Revision ID: d2978cc4bf58
Revises: 614796f0d734
Create Date: 2025-11-21 16:21:49.920210

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d2978cc4bf58"
down_revision = "614796f0d734"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_runs_team_assistant_created_at",
        "runs",
        ["team_id", "assistant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_runs_thread_team_created_at",
        "runs",
        ["thread_id", "team_id", "created_at"],
        unique=False,
    )
    op.add_column(
        "thread",
        sa.Column(
            "is_shared", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column("thread", sa.Column("assistant_id", sa.Text(), nullable=True))
    op.create_index("idx_thread_assistant", "thread", ["assistant_id"], unique=False)
    op.create_index(
        "idx_thread_team_assistant", "thread", ["team_id", "assistant_id"], unique=False
    )
    op.create_index(
        "idx_thread_team_assistant_created_at",
        "thread",
        ["team_id", "assistant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_thread_team_is_shared", "thread", ["team_id", "is_shared"], unique=False
    )
    op.create_index(
        "idx_thread_user_assistant", "thread", ["user_id", "assistant_id"], unique=False
    )
    # Backfill assistant_id for existing threads from metadata_json.assistant_id (PostgreSQL JSONB)
    op.execute(
        """
        UPDATE thread
        SET assistant_id = metadata_json->>'assistant_id'
        WHERE assistant_id IS NULL
          AND metadata_json ? 'assistant_id'
        """
    )
    op.create_foreign_key(
        "thread_assistant_id_fk",
        "thread",
        "assistant",
        ["assistant_id"],
        ["assistant_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("thread_assistant_id_fk", "thread", type_="foreignkey")
    op.drop_index("idx_thread_user_assistant", table_name="thread")
    op.drop_index("idx_thread_team_is_shared", table_name="thread")
    op.drop_index("idx_thread_team_assistant_created_at", table_name="thread")
    op.drop_index("idx_thread_team_assistant", table_name="thread")
    op.drop_index("idx_thread_assistant", table_name="thread")
    op.drop_column("thread", "assistant_id")
    op.drop_column("thread", "is_shared")
    op.drop_index("idx_runs_thread_team_created_at", table_name="runs")
    op.drop_index("idx_runs_team_assistant_created_at", table_name="runs")
    # ### end Alembic commands ###
