"""add_enabled_field_to_assistant

Revision ID: f539a8f934fb
Revises: 5bd3eabf71a9
Create Date: 2026-02-10 09:07:21.267151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f539a8f934fb'
down_revision = '5bd3eabf71a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant', sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index('idx_assistant_enabled', 'assistant', ['enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_assistant_enabled', table_name='assistant')
    op.drop_column('assistant', 'enabled')
    # ### end Alembic commands ###
