"""add workflows and workflow_runs tables

Revision ID: a2794b43fa4b
Revises: a1b2c3d4e5f6
Create Date: 2026-03-18 15:53:16.618793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2794b43fa4b'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.Text(), server_default=sa.text('uuid_generate_v4()::text'), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_is_active', 'workflows', ['is_active'], unique=False)
    op.create_index('idx_workflow_team', 'workflows', ['team_id'], unique=False)
    op.create_index('idx_workflow_team_user', 'workflows', ['team_id', 'user_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Text(), server_default=sa.text('uuid_generate_v4()::text'), nullable=False),
    sa.Column('workflow_id', sa.Text(), nullable=False),
    sa.Column('team_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_run_created_at', 'workflow_runs', ['created_at'], unique=False)
    op.create_index('idx_workflow_run_status', 'workflow_runs', ['status'], unique=False)
    op.create_index('idx_workflow_run_team', 'workflow_runs', ['team_id'], unique=False)
    op.create_index('idx_workflow_run_team_workflow', 'workflow_runs', ['team_id', 'workflow_id'], unique=False)
    op.create_index('idx_workflow_run_workflow', 'workflow_runs', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('idx_workflow_run_workflow', table_name='workflow_runs')
    op.drop_index('idx_workflow_run_team_workflow', table_name='workflow_runs')
    op.drop_index('idx_workflow_run_team', table_name='workflow_runs')
    op.drop_index('idx_workflow_run_status', table_name='workflow_runs')
    op.drop_index('idx_workflow_run_created_at', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index('idx_workflow_team_user', table_name='workflows')
    op.drop_index('idx_workflow_team', table_name='workflows')
    op.drop_index('idx_workflow_is_active', table_name='workflows')
    op.drop_table('workflows')
