"""add_deleted_at_columnt_to_threads

Revision ID: 5bd3eabf71a9
Revises: add_type_field
Create Date: 2026-01-06 05:37:43.592184

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5bd3eabf71a9"
down_revision = "add_type_field"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("thread", sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_index("idx_thread_deleted_at", "thread", ["deleted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_thread_deleted_at", table_name="thread")
    op.drop_column("thread", "deleted_at")
    # ### end Alembic commands ###
