name: Build And Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to Run"
        required: true
        type: choice
        options:
          - solwey-qa
          - solwey-prod
  workflow_call:
    inputs:
      env:
        description: "Environment to Run"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    environment: ${{ github.event.inputs.env || inputs.env }}
    runs-on: ${{ vars.RUNNER_TYPE }}
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      SECRET_NAME_ENV: ${{ vars.SECRET_NAME_ENV }}
      SECRET_NAME_CI: ${{ vars.SECRET_NAME_CI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.IAMROLE_GITHUB_QA }}
          role-session-name: GitHubActionsSession

      - name: Fetch AWS secret values
        run: |
          aws secretsmanager get-secret-value --region $AWS_REGION --secret-id $SECRET_NAME_CI --query SecretString --output text | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> $GITHUB_ENV

      - name: Create .env file
        run: |
          aws secretsmanager get-secret-value --region $AWS_REGION --secret-id $SECRET_NAME_ENV --query SecretString --output text | jq -r 'keys[] as $k | "\($k)=\"\(.[$k])\""' > $DOTENV_FNAME

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR (APP)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          build-args: |
            ENV_FILE=${{ env.DOTENV_FNAME }}
          tags: |
            ${{ env.IMG_TAG }}
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.DOCKER_REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ env.DOCKER_REPOSITORY }}:buildcache,mode=max

      - name: Restart EKS deployment
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
          kubectl rollout restart deployment $DEPLOYMENT_NAME -n $NAMESPACE
          kubectl rollout status deployment $DEPLOYMENT_NAME -n $NAMESPACE

          kubectl rollout restart deployment $DEPLOYMENT_NAME_WORKER -n $NAMESPACE
          kubectl rollout status deployment $DEPLOYMENT_NAME_WORKER -n $NAMESPACE

          kubectl rollout restart deployment $DEPLOYMENT_NAME_BEAT -n $NAMESPACE
          kubectl rollout status deployment $DEPLOYMENT_NAME_BEAT -n $NAMESPACE

      - name: Notify in Slack
        run: |
          export SLACK_TITLE="STAGING APP"
          export SLACK_MSG="New version is live."
          ./scripts/_send-slack-msg.sh
